apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.name }}-v2
spec:
  minAvailable: {{ .Values.spec.minAvailable }}
  selector:
    matchLabels:
      s6charlsee: {{ .Values.labels.s6charlsee }}